version: '3.5'

services:
    
  backend:
    container_name: kaisir_backend
    image: denitiawan/kaisir-backend:latest-prod
    environment:           
     
        KAISIR_HOST: 'host.docker.internal'
        KAISIR_PORT: '8181'

        KAISIR_DB_HOST: 'host.docker.internal'
        KAISIR_DB_PORT: '3307'
        KAISIR_DB_USER: 'user'
        KAISIR_DB_PASSWORD: 'password'
        KAISIR_DB_NAME: 'db_kaisir'

        KAISIR_REDIS_HOST: 'host.docker.internal'
        KAISIR_REDIS_PORT: '6379'
        KAISIR_REDIS_USERNAME: 'user'
        KAISIR_REDIS_PASSWORD: 'password123'
        
        KAISIR_ALLOWORIGINS_CLIENT_URL: 'http://kaisirpos.my.id'
        #KAISIR_ALLOWORIGINS_CLIENT_URL: 'http://localhost:1991'
              
      
    ports:      
      - '8181:8181'
    expose:      
      - '8181'      
    #networks:
    #  - pos_env_network
      
    #depends_on:
    #  - pos_env_redis
    #  - pos_env_mysql
      
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.5   
    
    
     
 