{
 "title": "Dashboard Counter",
 "description": "Counter",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Counter Http Request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "200 : SUCCESS",
   "type": "singlestat",
   "description": "the APIs is success ",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{status=\"200\"})"
    }
   ]
  },
  {
   "title": "400 : BAD REQUEST",
   "type": "singlestat",
   "description": "the request body is Invalid argument (invalid request payload)  when access the API ",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{status=\"400\"})"
    }
   ]
  },
  {
   "title": "401 : UNAUTHORIZE",
   "type": "singlestat",
   "description": "the username or password dont have credential for access the application",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{status=\"401\"})"
    }
   ]
  },
  {
   "title": "403 : FORBIDDEN",
   "type": "singlestat",
   "description": "the request token dont have permission for access the API",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{status=\"403\"})"
    }
   ]
  },
  {
   "title": "405 : METHOD NOT ALLOWED",
   "type": "singlestat",
   "description": "CORS : http method is not allowed by backend server",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{status=\"405\"})"
    }
   ]
  },
  {
   "title": "429 : RATE LIMMITER",
   "type": "singlestat",
   "description": "Too Many Request",
   "gridPos": { "h": 4, "w": 4, "x": 19, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{status=\"429\"})"
    }
   ]
  },
  {
   "title": "500 : INTERNAL SERVER ERROR",
   "type": "singlestat",
   "description": "Internal Server Error",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{status=\"500\"})"
    }
   ]
  },
  {
   "title": "503 : CIRCUIT BREAKER",
   "type": "singlestat",
   "description": "Too long wait time out",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{status=\"503\"})"
    }
   ]
  }
 ]
}