version: '3'

services:
        
  prometheus:
    image: prom/prometheus:v2.17.1
    container_name: pos_kaisir_prometheus   
    volumes:
        - ./prometheus:/etc/prometheus
        #- prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'   
    
    ports:      
      - 1001:9090
      
    #- 9090:9090
    
    networks:
      - pos_env_network  
      
   
      
    mem_limit: 256m
    mem_reservation: 128M
    cpus: 0.1 
  
  grafana:
    image: grafana/grafana:6.7.2
    container_name: pos_kaisir_grafana
    volumes:
      #- grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    #environment:
      #- GF_SECURITY_ADMIN_USER=admin
      #- GF_SECURITY_ADMIN_PASSWORD=admin
      #- GF_USERS_ALLOW_SIGN_UP=false
    
    ports:
      - 1002:3000
      
    #- 3000:3000
      
    expose:
      - 1002
    #- 3000
      
    networks:
      - pos_env_network  


    depends_on:
      - prometheus      
      
    mem_limit: 256m
    mem_reservation: 128M
    cpus: 0.1 

              
      
networks:  
  pos_env_network:    
    name: pos_env_network
    driver: bridge
  
    
  